# GET request that gets list of all contacts
GET http://localhost:8001/yarns HTTP/1.1

GET http://localhost:8001/patterns HTTP/1.1

GET http://localhost:8001/yarns/63364027c6b4ac6ca4d33de8 HTTP/1.1


# Format expected:
# {
# "yarnName":"Wool of The Andes",
# "yarnBrand":"Knit Picks",
# "size":"50g / 1.75 oz, 91 meters / 100 yards",
# "recHookNeedleSize":
# {"needleSize":"6-9 needles","hookSize":"I-K hooks"},
# "colors":["Lullaby","Nightshade","Papaya"],
# "weight":4,
# "fiberType":"Wool"
# }
POST http://localhost:8001/yarns HTTP/1.1

# PUT request that updates an existing contact with ID 632a0aa66fb797661375f88a
# Format expected is more or less like the POST request
PUT http://localhost:8001/yarns/6336406cc6b4ac6ca4d33de9 HTTP/1.1

# DELETE request that deletes an existing contact with ID 632a0aa66fb797661375f88a
DELETE http://localhost:8001/yarns/6338907bc1756100a09d624a HTTP/1.1



# Same requests but on render
GET https://projectyarn.onrender.com/contacts/ HTTP/1.1

GET https://projectyarn.onrender.com/contacts/ HTTP/1.1

POST https://projectyarn.onrender.com/contacts/ HTTP/1.1
{
"yarnName":"Wool of The Andes",
"yarnBrand":"Knit Picks",
"size":"50g / 1.75 oz, 91 meters / 100 yards",
"recHookNeedleSize":
{"needleSize":"6-9 needles","hookSize":"I-K hooks"},
"colors":["Lullaby","Nightshade","Papaya"],
"weight":4,
"fiberType":"Wool"
}

PUT https://projectyarn.onrender.com/contacts/ HTTP/1.1

DELETE https://cse341-norseth.onrender.com/contacts/ HTTP/1.1